name: build

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    paths-ignore:
      - 'CHANGELOG.md'
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            build_script: .\build.ps1
          - os: ubuntu-latest
            build_script: ./build.sh
          - os: macos-latest
            build_script: ./build.sh

    steps:
        - name: Checkout
          uses: actions/checkout@v2.3.3
          with:
            submodules: recursive
            fetch-depth: 2 # default is 1 and codecov needs > 1

        - name: Setup .NET SDK (v2.1)
          uses: actions/setup-dotnet@v1.7.2
          with:
            dotnet-version: '2.1.809'
        - name: Setup .NET SDK (v3.1)
          uses: actions/setup-dotnet@v1.7.2
          with:
            dotnet-version: '3.1.401'
        - name: Setup .NET SDK (v5.0)
          uses: actions/setup-dotnet@v1.7.2
          with:
            dotnet-version: '5.0.100'
        - name: Setup .NET SDK (v6.0)
          uses: actions/setup-dotnet@v1.7.2
          with:
            dotnet-version: '6.0.100-preview.5.21302.13'

        - name: Install JDK 1.8
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '8'

        - name: Install workloads on macOS
          if: matrix.os == 'macos-latest'
          run: |
            sudo dotnet workload install ios tvos macos maccatalyst android

        - name: Install workloads on Linux
          if: matrix.os == 'ubuntu-latest'
          run: |
            dotnet workload install android

        - name: Install workloads on Windows
          if: matrix.os == 'windows-latest'
          run: |
            dotnet workload install android

        - name: Run build script
          run: ${{ matrix.build_script }}

        - name: Publish coverage report
          uses: codecov/codecov-action@v1

        - name: Archive Artifacts
          # only the ps1 script packages the SDK
          if: matrix.os == 'windows-latest'
          uses: actions/upload-artifact@v2
          with:
            name: ${{ github.sha }}
            path: |
              ${{ github.workspace }}/src/**/Release/*.nupkg

